#!/usr/bin/env python3
"""Tests for config_generator.py - validation coverage."""
import json, sys, os, unittest
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from tools.config_generator import (
    DEFAULT_CONFIG, ENV_OVERRIDES, SENSITIVE_KEYS,
    merge_config, generate_config, mask_sensitive,
    to_yaml, to_json, to_toml, to_dotenv,
    to_k8s_configmap, flatten_for_k8s,
)
try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False
try:
    import toml
    HAS_TOML = True
except ImportError:
    HAS_TOML = False

class TestSensitiveKeys(unittest.TestCase):
    def test_no_duplicates(self):
        seen = set()
        for key in SENSITIVE_KEYS:
            self.assertNotIn(key, seen, f"Duplicate SENSITIVE_KEY: {key}")
            seen.add(key)

    def test_all_keys_exist(self):
        flat = {}
        def _fl(d, p=""):
            for k, v in d.items():
                fk = f"{p}.{k}" if p else k
                if isinstance(v, dict): _fl(v, fk)
                else: flat[fk] = v
        _fl(DEFAULT_CONFIG)
        for sk in SENSITIVE_KEYS:
            self.assertIn(sk, flat)

    def test_keys_are_empty(self):
        flat = {}
        def _fl(d, p=""):
            for k, v in d.items():
                fk = f"{p}.{k}" if p else k
                if isinstance(v, dict): _fl(v, fk)
                else: flat[fk] = v
        _fl(DEFAULT_CONFIG)
        for sk in SENSITIVE_KEYS:
            self.assertEqual(flat[sk], "")

class TestMergeConfig(unittest.TestCase):
    def test_simple(self):
        self.assertEqual(merge_config({"a":1,"b":2},{"b":3,"c":4}), {"a":1,"b":3,"c":4})
    def test_nested(self):
        r = merge_config({"db":{"host":"localhost","port":5432}}, {"db":{"port":5433}})
        self.assertEqual(r["db"]["host"],"localhost") and self.assertEqual(r["db"]["port"],5433)

class TestGenerateConfig(unittest.TestCase):
    def test_default_is_dev(self):
        self.assertEqual(generate_config("development")["app"]["environment"],"development")
    def test_production_no_debug(self):
        self.assertFalse(generate_config("production")["app"]["debug"])
    def test_custom_override(self):
        self.assertEqual(generate_config("production",{"app":{"name":"custom"}})["app"]["name"],"custom")

class TestMaskSensitive(unittest.TestCase):
    def test_password_masked(self):
        self.assertEqual(mask_sensitive({"database":{"password":"x"}})["database"]["password"],"***REDACTED***")
    def test_non_sensitive_unchanged(self):
        self.assertEqual(mask_sensitive({"app":{"name":"test"}})["app"]["name"],"test")

class TestToJson(unittest.TestCase):
    def test_output(self):
        self.assertEqual(json.loads(to_json({"a":1}))["a"],1)
    def test_compact(self):
        self.assertNotIn("\n",to_json({"a":1},pretty=False))

class TestToDotenv(unittest.TestCase):
    def test_output(self):
        self.assertIn("APP_NAME=test", to_dotenv({"app":{"name":"test"}}).replace(" ",""))
    def test_header(self):
        self.assertIn("# Generated by config_generator.py", to_dotenv({"app":{"name":"test"}}))

class TestToK8sConfigmap(unittest.TestCase):
    def test_kind(self):
        self.assertIn("kind: ConfigMap", to_k8s_configmap({"a":"b"}))
    def test_custom_name(self):
        self.assertIn("name: my-cfg", to_k8s_configmap({"a":"b"},name="my-cfg"))

class TestAllEnvsValid(unittest.TestCase):
    def test_all_envs(self):
        for env in ENV_OVERRIDES:
            c = generate_config(env)
            self.assertIsInstance(c,dict)
            self.assertGreater(c["server"]["port"],0)

if __name__ == "__main__":
    unittest.main()
